### ISSUE TITLE
Compile errors for ziptastic-core

### ISSUE THREAD

**Issue by hvr** [Ziptastic/ziptastic-haskell#4]
Hi, I just noticed on http://104.239.175.197:8080/package/ziptastic-core that `ziptastic-core` fails to build:

```
Configuring component lib from ziptastic-core-0.1.0.1...
Preprocessing library ziptastic-core-0.1.0.1...

src/Ziptastic/Core.hs:7:5:
    Cannot parse LANGUAGE pragma
    Expecting comma-separated list of language options,
    each starting with a capital letter
      E.g. {-# LANGUAGE TemplateHaskell, GADTs #-}
```

PS: If you're interested, I can help you setup https://github.com/hvr/multi-ghc-travis to catch such issues earlier

**Comment by 3noch** [comment]
@hvr Wow. I'd love help getting Travis CI setup as that's already on my list (see #3). Since I have two packages in the same repo, I wasn't sure if your script would work for my repo.

About the compile error, what version of `cabal` are you using? It builds fine for me with `stack` (although I am excited to use `cabal new-build`).

Could it be that some versions don't like how I've formatted the pragmas?

```haskell
{-# LANGUAGE
    DataKinds
  , DeriveGeneric
  , FlexibleInstances
  , GeneralizedNewtypeDeriving
  , OverloadedStrings
  , TypeOperators
#-}
```

**Comment by 3noch** [comment]
P.S. That matrix builder tool looks awesome! It doesn't have a domain though. If there's any way I can help out let me know.

**Comment by hvr** [comment]
@3noch oh... now I remember... the problem is that older GHC versions' lexer/unlitter got confused when there is a `#` in the first column. Just indent the `#-}` by at least one whitespace, and it should work.

As for Travis; yes, my script probably doesn't work yet properly for multi-package projects out of the box. But I'm working on a variant that does, and for that I need a few real-world use-cases so I can figure out a common pattern.

So if you could just go to https://travis-ci.org/profile/3noch and enable Travis for this repo, then I can create a PR against this repo and quickly set up a CI config (with a little bit of trial&error).

The reason _that_ matrix website doesn't have an IP address yet is because it's the next-gen work-in-progress version of http://matrix.hackage.haskell.org/ ... :-)

**Comment by 3noch** [comment]
Thanks for info. As for setting up CI, that sounds like a great bargain indeed! Travis is enabled! https://travis-ci.org/Ziptastic/ziptastic-haskell/

Re: Matrix; Aha...that's a very exciting development!

**Comment by 3noch** [comment]
`LANGUAGE` pragmas now use a less crazy format.

**Comment by 3noch** [comment]
@hvr It occurs to me: Why use travis at all when you have this amazing build matrix?

**Comment by hvr** [comment]
@3noch cause the matrix-builder doesn't catch errors early enough... travis helps you verify each single commit and each PR. Moreover, the matrix builder doesn't run tests... :-)

**Comment by 3noch** [comment]
@hvr Ah makes sense.

**Comment by 3noch** [comment]
Fixed by https://github.com/Ziptastic/ziptastic-haskell/commit/6ed0cbc384d765c9069dc098cb9e951c94fc7c1a
